name: macropad

services:
  build-macropad:
    build:
      context: .
    init: true
    user: root
    working_dir: /workspace
    environment:
      OUTPUT_DIR: /out
      BUILD_CACHE_DIR: /cache
      HOST_UID: ${HOST_UID:-1000}
      HOST_GID: ${HOST_GID:-1000}
      QMK_REPO: ${QMK_REPO:-https://github.com/FrameworkComputer/qmk_firmware.git}
      QMK_REF:  ${QMK_REF:-fl16-2025}
      KEYBOARD: ${KEYBOARD:-framework/macropad}
      KEYMAP:   ${KEYMAP:-phlax}
      FLASH:    ${FLASH:-}
    volumes:
      - ./workspace:/workspace
      - ./out:/out
      - ./cache:/cache
      - ./keymap:/repo/keymap:ro
      - ./scripts:/repo/scripts:ro
    command: ["/bin/bash", "/repo/scripts/build-macropad.sh"]
